<?php

require_once dirname(__FILE__) . '/../../../application/models/User.php';

/**
 * Test class for Model_User.
 * Generated by PHPUnit on 2012-04-09 at 17:28:21.
 */
class Model_UserTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Model_User
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Model_User;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testFetch().
	 */
	public function testFetch() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetUserActivity().
	 */
	public function testGetUserActivity() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @covers {className}::{origMethodName}
	 * @todo Implement testGetFriendRequests().
	 */
	public function testGetFriendRequests() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

