<!DOCTYPE html>
<html lang="en">
	<head>
		<?php echo $this->headTitle(); ?>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
		<meta name="keywords" content="" />
		<meta name="description" content="" />
		<link rel="stylesheet" href="/css/reset.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/css/styles.css" type="text/css" media="all" />
		<script type="text/javascript">
			//<!--
				document.getElementsByTagName('html')[0].className += ' js';
			//-->
		</script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	</head>
	<body>
		<div id="Main">
			<div id="Content">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
	</body>
</html>