<form id="calculator" action="#" method="post">
    <h1><?php echo $this->translate('Calculator'); ?></h1>
    <p>
        <?php echo $this->translate('Please enter two numbers below and a mathmatical operator.'); ?>
    </p>
    <fieldset>
        <div class="row">

            <div class="form-group col-sm-4">
                <label for="val1">
                    <?php echo $this->translate('Number 1'); ?>
                </label>
                <input type="number" name="val1" id="val1" value="<?php echo $this->form->getValue('val1'); ?>" step="0.0000001">
            </div>

            <div class="form-group col-sm-4">
                <label for="operator"><?php echo $this->translate('operator'); ?></label>
                <select id="operator" name="operator">
                    <option value="ADDITION" <?php 	echo $this->form->getValue('operator') === 'ADDITION' ? 'selected' : ''; ?>>+</option>
                    <option value="SUBTRACT" <?php 	echo $this->form->getValue('operator') === 'SUBTRACT' ? 'selected' : ''; ?>>-</option>
                    <option value="MULTIPLY" <?php 	echo $this->form->getValue('operator') === 'MULTIPLY' ? 'selected' : ''; ?>>&times;</option>
                    <option value="DIVIDE" <?php 	echo $this->form->getValue('operator') === 'DIVIDE' ? 'selected' : ''; ?>>&divide;</option>
                </select>
            </div>

            <div class="form-group col-sm-4">
                <label for="val2">
                    <?php echo $this->translate('Number 2'); ?>
                </label>
                <input type="number" name="val2" id="val2" value="<?php echo $this->form->getValue('val2'); ?>" step="0.0000001">
            </div>
            <button type="submit" class="btn btn-primary"><?php echo $this->translate('Calculate'); ?></button>
        </div>

        <?php if ($this->result !== null): ?>
            <div id="result" class="alert alert-primary" role="alert">
                <?php echo $this->translate('Your result'); ?>:

				<?php echo $this->form->getValue('val1'); ?>
				<?php echo $this->mathSymbol($this->form->getValue('operator')); ?>
				<?php echo $this->form->getValue('val2'); ?>
				=
                <b><?php echo $this->result; ?></b>
            </div>
        <?php endif; ?>

        <?php if ($this->errors): ?>
            <div id="errors" class="alert alert-danger" role="alert">
			<?php foreach ($this->errors AS $error): ?>
				<?php foreach ($error AS $message): ?>
				<p>
					<?php echo($message); ?>
				</p>
				<?php endforeach; ?>
			<?php endforeach; ?>
			</div>
        <?php endif; ?>
    </fieldset>
	<div id="Copyright">&copy; 2019 Andrew Fisher</div>
</form>